name: CitiTrader
main:  me.tehbeard.cititrader.CitiTrader
version: 0.1-Beta-5
depend: [Citizens,Vault]
commands:
    trader:
        description: CitiTrader commands 
        usage: |
          /<command> create name -type [TYPE] - Create a trader at the players current location
          /<command> fire - fire an npc
          /<command> setwallet [private|owner|bank|admin] accountname - set wallet type
          /<command> wallet [give|take] amount  - place/remove money from a private wallet
          /<command> sellprice price - Set selling price for item currently in hand, right click npc to set price for them.
          /<command> buyprice price - Set buying price for item currently in hand, right click npc to set price for them.
        
permissions:
  traders.command.*:
    description: Grants access to all trader commands
    default: op
    children:
      traders.command.create: true
      traders.command.sellprice: true
      traders.command.buyprice: true
      traders.command.fire: true
  traders.command.create:
    description: Can create traders using /trader create
    default: op
  traders.command.sellprice:
    description: can set sale prices of traders
    default: op
  traders.command.buyprice:
    description: Can set purchase orders
    default: op
  traders.command.setwallet:
    description: Set an npc's wallet type
    default: op
  traders.command.wallet:
    description: Give/take from an npc wallet.
    default: op
  traders.wallet.private:
    description: Allows user to set traders to use their own private wallet.
    default: true
  traders.wallet.owner:
    description: Allows user to set traders to use their owner's bank wallet.
    default: true  
  traders.wallet.bank:
    description: Allows user to set traders to use a bank account (ECONOMY PLUGIN MUST SUPPORT BANKS, USER MUST OWN BANK ACCOUNT).
    default: true 
  traders.wallet.admin:
    description: Allows user to set traders to use a bank account (ECONOMY PLUGIN MUST SUPPORT BANKS, USER MUST OWN BANK ACCOUNT).
    default: op